### PR TITLE
fix: universal navbar errors fix

### PR DESCRIPTION
**Pull request by darkul1**
### Please review these reminders and either check the box or explain why not:

- [ ] Read and followed the [contributing guidelines](https://eds.eks.dev.ethos-int.com/#/Guidelines?id=section-contribute)?
- [ ] Component is exported from [index.js](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.js)?
- [ ] Type is exported from [index.d.ts](https://github.com/getethos/ethos-design-system/blob/master/src/components/index.d.ts) so Typescript users can consume it? Added a test and ran `yarn test:types`?
- [ ] Bumped the yarn version?

### Referencing PR or Branch (e.g. in CMS or monorepo):

- https://github.com/getethos/cms-next/pull/219

### Screenshots and extra notes:
Just updated keys logic.

### CODE REVIEW

**Review by coleEthos — CHANGES_REQUESTED** [review]
@darkul1 were these :root -> .body and other changes tested to be compatible with main application? We might need to merge this to cms-next branch instead of master.

**Comment by coleEthos** [comment]
Merged https://github.com/getethos/ethos-design-system/pull/509 so will have to bump version here to 1.3.28

**Comment by darkul1** [comment]
@coleEthos this PR will not be merged into main, this PR is only for CMS-next showcase. (I will close this one)

**Comment by coleEthos** [comment]
@darkul1 got it!

**Pull request closed without merging**
